 
ALTER TABLE VENTE 
ADD PLANPAIEMENT VARCHAR2(200); 


drop view INSERTION_VENTE ; 


CREATE OR REPLACE FORCE VIEW "SOCOBIS"."INSERTION_VENTE"
("ID", "DESIGNATION", "IDMAGASIN", "DATY", "REMARQUE", "ETAT", "IDORIGINE",
 "IDCLIENT", "IDDEVISE", "ESTPREVU", "DATYPREVU", "IDRESERVATION",
 "ECHEANCEFACTURE", "MODEPAIEMENT", "MODELIVRAISON", "FRAISLIVRAISON",
 "REFERENCEFACT", "PLANPAIEMENT") AS
SELECT
    v.ID,
    v.DESIGNATION,
    v.IDMAGASIN,
    v.DATY,
    v.REMARQUE,
    v.ETAT,
    v.IDORIGINE,
    v.IDCLIENT,
    CAST(' ' AS varchar(100)) AS iddevise,
    v.ESTPREVU,
    v.DATYPREVU,
    v.IDRESERVATION,
    v.echeancefacture,
    v.modepaiement,
    v.modelivraison,
    v.fraislivraison,
    v.referencefact,
    v.planpaiement
FROM VENTE v;
